version: "3"
services:
  db:
    container_name: db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ig-db
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - data:/var/lib/postgresql/data
  redis:
    container_name: cache
    image: "redis:7-alpine"
    restart: always
    ports:
      - "6378:6379"
    volumes:
      - cache:/data
volumes:
  cache:
  data:
